version: '3'

vars:
  SERVICE_NAME: order
  GOBIN: $(pwd)/bin
  GOLANGCI_LINT_VERSION: v2.5

tasks:
  default:
    cmds:
      - task: fmt
      - task: lint
      - task: build

  install-tools:
    desc: install development tools
    cmds:
      - GOBIN={{ .GOBIN }} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{ .GOLANGCI_LINT_VERSION }}
    silent: true

  fmt:
    desc: format code
    cmds:
      - gofmt -w -l .

  lint:
    desc: lint code with golangci-lint
    deps: [install-tools]
    cmds:
      - "{{ .GOBIN }}/golangci-lint run --timeout 5m ./..."

  build:
    desc: build the application
    cmds:
      - go build -o ./bin/{{ .SERVICE_NAME }} ./cmd/app

  run:
    desc: run the application (requires PostgreSQL)
    cmds:
      - go run ./cmd/app

  test:
    desc: run tests
    cmds:
      - go test -race ./...

  # Docker/Podman infrastructure
  infra-up:
    desc: start PostgreSQL with docker-compose
    cmds:
      - docker-compose -f docker-compose.yml up -d

  infra-down:
    desc: stop PostgreSQL
    cmds:
      - docker-compose -f docker-compose.yml down

  podman-infra-up:
    desc: start PostgreSQL with podman-compose
    cmds:
      - podman-compose -f docker-compose.yml up

  podman-infra-down:
    desc: stop PostgreSQL with podman-compose
    cmds:
      - podman-compose -f docker-compose.yml down

  # Combined commands
  run-all:
    desc: run the app
    cmds:
      - task: kill-all
      - task: run

  kill-all:
    desc: "kill all processes (app, mock, and state manager)"
    cmds:
      - kill -9 $(lsof -ti :8081) || true